// <auto-generated />
using System;
using CommercialShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommercialShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109001422_updateImage")]
    partial class updateImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Jackets",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Jerseys",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Scarves",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Tops",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Training",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Footwear",
                            gender = "Female"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Jackets",
                            gender = "Male"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Jerseys",
                            gender = "Male"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Tops",
                            gender = "Male"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Training",
                            gender = "Male"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Footwear",
                            gender = "Male"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Trousers & Shorts",
                            gender = "Male"
                        });
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ItemVariant", b =>
                {
                    b.Property<Guid>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("VariantId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ProductId", "SizeId")
                        .IsUnique();

                    b.ToTable("ItemVariants");

                    b.HasData(
                        new
                        {
                            VariantId = new Guid("4d8f2c52-3f9c-6f90-d9c9-333333333333"),
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111"),
                            SizeId = 1,
                            StockQuantity = 21
                        },
                        new
                        {
                            VariantId = new Guid("5e9f3d63-4fad-7fa1-eada-444444444444"),
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111"),
                            SizeId = 2,
                            StockQuantity = 22
                        },
                        new
                        {
                            VariantId = new Guid("6faf4e74-5bbe-8fb2-fbeb-555555555555"),
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111"),
                            SizeId = 3,
                            StockQuantity = 29
                        },
                        new
                        {
                            VariantId = new Guid("70a05f85-6ccf-9fc3-0cbc-666666666666"),
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222"),
                            SizeId = 1,
                            StockQuantity = 23
                        },
                        new
                        {
                            VariantId = new Guid("81b16a96-7dd0-afd4-1cdc-777777777777"),
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222"),
                            SizeId = 2,
                            StockQuantity = 25
                        },
                        new
                        {
                            VariantId = new Guid("92c27ba7-8ee1-bfe5-2ded-888888888888"),
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222"),
                            SizeId = 3,
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111"),
                            CategoryId = 4,
                            Price = 172.00m,
                            ProductDescription = "Official 2025-26 Away Stadium Shirt.",
                            ProductName = "Chelsea Nike Away Stadium Shirt 2025-26"
                        },
                        new
                        {
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222"),
                            CategoryId = 9,
                            Price = 172.00m,
                            ProductDescription = "Official 2025-26 Away Stadium Shirt.",
                            ProductName = "Chelsea Nike Stadium Shirt 2025-26"
                        });
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ProductDetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShownFirst")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImagePath = "/Image/Women/Top/womenHomeShirt.png",
                            IsShownFirst = true,
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111")
                        },
                        new
                        {
                            ImageId = 3,
                            ImagePath = "/Image/HomePage/game.png",
                            IsShownFirst = false,
                            ProductId = new Guid("2b6f0a30-1f7a-4d7f-b9a7-111111111111")
                        },
                        new
                        {
                            ImageId = 2,
                            ImagePath = "/Image/Men/Top/ChelseaAwayTshirt.png",
                            IsShownFirst = true,
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222")
                        },
                        new
                        {
                            ImageId = 4,
                            ImagePath = "/Image/HomePage/kit1.png",
                            IsShownFirst = true,
                            ProductId = new Guid("3c7f1b41-2f8b-5e8f-c8b8-222222222222")
                        });
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("CodeSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SizeId");

                    b.HasIndex("CodeSize")
                        .IsUnique();

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            CodeSize = "S"
                        },
                        new
                        {
                            SizeId = 2,
                            CodeSize = "M"
                        },
                        new
                        {
                            SizeId = 3,
                            CodeSize = "L"
                        },
                        new
                        {
                            SizeId = 4,
                            CodeSize = "XL"
                        },
                        new
                        {
                            SizeId = 5,
                            CodeSize = "2XL"
                        },
                        new
                        {
                            SizeId = 6,
                            CodeSize = "3XL"
                        });
                });

            modelBuilder.Entity("CommercialShop.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ItemVariant", b =>
                {
                    b.HasOne("CommercialShop.Models.ProductModel.Product", "product")
                        .WithMany("itemVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommercialShop.Models.ProductModel.Size", "size")
                        .WithMany("itemVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("size");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Product", b =>
                {
                    b.HasOne("CommercialShop.Models.ProductModel.Categories", "categories")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("categories");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ProductDetails", b =>
                {
                    b.HasOne("CommercialShop.Models.ProductModel.Product", "product")
                        .WithMany("details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.ProductImage", b =>
                {
                    b.HasOne("CommercialShop.Models.ProductModel.Product", "product")
                        .WithMany("images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CommercialShop.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CommercialShop.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommercialShop.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CommercialShop.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Product", b =>
                {
                    b.Navigation("details");

                    b.Navigation("images");

                    b.Navigation("itemVariants");
                });

            modelBuilder.Entity("CommercialShop.Models.ProductModel.Size", b =>
                {
                    b.Navigation("itemVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
